### ISSUE TITLE
StackOverflowError in ByteCodeSwitch.caseInvokeCbS(ByteCodeSwitch.java:1751)

### ISSUE THREAD

**Issue by dwagelaar** [eclipse-atl/atl#1]
When running the following SimpleOCL code in EMFTVM, it triggers a StackOverflowError in the JIT compiler:

```
module Extensions2;

context Bag(OclAny) def : closure(f : Lambda(OclAny): OclAny) : Bag(OclAny) = 
	let buffer: Bag(OclAny) = self->collect(e | f(e))->reject(e | e.oclIsUndefined())->flatten() in
	if buffer->isEmpty() then
		self
	else
		self->union(buffer->closure(f))
	endif;

context Integer def : minusOne : Integer =
	if self = 0 then
		OclUndefined
	else
		self - 1
	endif;

context Integer def : minusOnes : Bag(Integer) =
	if self = 0 then
		OclUndefined
	else
		let this : Integer = self - 1 in
		Bag{this, this.minusOnes}->reject(e | e.oclIsUndefined())->flatten()
	endif;

static def : test() : OclAny =
	Bag{5,4,3,2,1}->closure(e | e.minusOne);

static def : test2() : OclAny =
	Bag{5,4,3,2,1}->closure(e | e.minusOnes);

static def : main() : OclAny =
	Sequence{Env::test(), Env::test2()}.debug();
```
Stack trace:
```
Exception in thread "Thread-11" java.lang.StackOverflowError
	at org.objectweb.asm.Type.appendDescriptor(Type.java:601)
	at org.objectweb.asm.Type.getDescriptor(Type.java:522)
	at org.objectweb.asm.Type.getType(Type.java:210)
	at org.eclipse.m2m.atl.emftvm.jit.ByteCodeSwitch.invoke(ByteCodeSwitch.java:2277)
	at org.eclipse.m2m.atl.emftvm.jit.ByteCodeSwitch.invokeVirt(ByteCodeSwitch.java:2295)
	at org.eclipse.m2m.atl.emftvm.jit.ByteCodeSwitch.caseInvokeCbS(ByteCodeSwitch.java:1699)
	at org.eclipse.m2m.atl.emftvm.jit.ByteCodeSwitch.caseInvokeCbS(ByteCodeSwitch.java:1751)
	at org.eclipse.m2m.atl.emftvm.jit.ByteCodeSwitch.caseInvokeCbS(ByteCodeSwitch.java:1751)
	at org.eclipse.m2m.atl.emftvm.jit.ByteCodeSwitch.caseInvokeCbS(ByteCodeSwitch.java:1751)
	at org.eclipse.m2m.atl.emftvm.jit.ByteCodeSwitch.caseInvokeCbS(ByteCodeSwitch.java:1751)
	at org.eclipse.m2m.atl.emftvm.jit.ByteCodeSwitch.caseInvokeCbS(ByteCodeSwitch.java:1751)
...
```

**Comment by dwagelaar** [comment]
Caused by missing `super` on line 1751:
```java
		return caseInvokeCbS(object);
```
should be
```java
		return super.caseInvokeCbS(object);
```
