### ISSUE TITLE
Deleting contained model elements in refining mode throws NPE

### ISSUE THREAD

**Issue by dwagelaar** [eclipse-atl/atl#20]
When deleting nested model elements in refining mode, a NullPointerException can occur:

```
  [emftvm.run] org.eclipse.m2m.atl.emftvm.util.VMException: Error deleting Administration:UML!Package.ownedComment from 34cfc7aa:UML!Comment: Cannot invoke "org.eclipse.emf.ecore.resource.Resource.getContents()" because the return value of "org.eclipse.emf.ecore.EObject.eResource()" is null
  [emftvm.run] at rule removes@applier#1(/StandardProfileConvertor_Gen/StandardProfile_Convertor.atl#[61:7-61:23])
  [emftvm.run] 	Local variables: [__trace__: TRACE!TraceLink = 48a2104e:TRACE!TraceLink, src: UML!Element = 34cfc7aa:UML!Comment]
  [emftvm.run] at static EMFTVM!ExecEnv::main() : Object(/StandardProfileConvertor_Gen/StandardProfile_Convertor.atl)
  [emftvm.run] 	Local variables: []
  [emftvm.run] 	at org.eclipse.m2m.atl.emftvm.impl.ExecEnvImpl$DeletionEntry.process(ExecEnvImpl.java:227)
  [emftvm.run] 	at org.eclipse.m2m.atl.emftvm.impl.ExecEnvImpl.deleteQueue(ExecEnvImpl.java:2383)
  [emftvm.run] 	at org.eclipse.m2m.atl.emftvm.impl.ExecEnvImpl.matchAllSingle(ExecEnvImpl.java:2239)
  [emftvm.run] 	at org.eclipse.m2m.atl.emftvm.impl.ExecEnvImpl.run(ExecEnvImpl.java:2075)
  [emftvm.run] 	at org.eclipse.m2m.atl.emftvm.ant.RunTask.runForOutputModelSet(RunTask.java:357)
  [emftvm.run] 	at org.eclipse.m2m.atl.emftvm.ant.RunTask.runForInOutModelSet(RunTask.java:320)
  [emftvm.run] 	at org.eclipse.m2m.atl.emftvm.ant.RunTask.runForInputModelSet(RunTask.java:298)
  [emftvm.run] 	at org.eclipse.m2m.atl.emftvm.ant.RunTask.innerExecute(RunTask.java:276)
  [emftvm.run] 	at org.eclipse.m2m.atl.emftvm.ant.EMFTVMTask.execute(EMFTVMTask.java:98)
  [emftvm.run] 	at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:299)
  [emftvm.run] 	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
  [emftvm.run] 	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
  [emftvm.run] 	at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:99)
  [emftvm.run] 	at org.apache.tools.ant.Task.perform(Task.java:350)
  [emftvm.run] 	at org.apache.tools.ant.Target.execute(Target.java:449)
  [emftvm.run] 	at org.apache.tools.ant.Target.performTasks(Target.java:470)
  [emftvm.run] 	at org.apache.tools.ant.Project.executeSortedTargets(Project.java:1401)
  [emftvm.run] 	at org.apache.tools.ant.Project.executeTarget(Project.java:1374)
  [emftvm.run] 	at org.apache.tools.ant.helper.DefaultExecutor.executeTargets(DefaultExecutor.java:41)
  [emftvm.run] 	at org.eclipse.ant.internal.core.ant.EclipseDefaultExecutor.executeTargets(EclipseDefaultExecutor.java:34)
  [emftvm.run] 	at org.apache.tools.ant.Project.executeTargets(Project.java:1264)
  [emftvm.run] 	at org.eclipse.ant.internal.core.ant.InternalAntRunner.run(InternalAntRunner.java:714)
  [emftvm.run] 	at org.eclipse.ant.internal.core.ant.InternalAntRunner.run(InternalAntRunner.java:530)
  [emftvm.run] 	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
  [emftvm.run] 	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
  [emftvm.run] 	at org.eclipse.ant.core.AntRunner.run(AntRunner.java:369)
  [emftvm.run] 	at org.eclipse.ant.internal.launching.launchConfigurations.AntLaunchDelegate.lambda$0(AntLaunchDelegate.java:279)
  [emftvm.run] 	at java.base/java.lang.Thread.run(Thread.java:1583)
  [emftvm.run] Caused by: java.lang.NullPointerException: Cannot invoke "org.eclipse.emf.ecore.resource.Resource.getContents()" because the return value of "org.eclipse.emf.ecore.EObject.eResource()" is null
  [emftvm.run] 	at org.eclipse.m2m.atl.emftvm.util.EMFTVMUtil.updateResource(EMFTVMUtil.java:1053)
  [emftvm.run] 	at org.eclipse.m2m.atl.emftvm.util.EMFTVMUtil.removeRefValue(EMFTVMUtil.java:1036)
  [emftvm.run] 	at org.eclipse.m2m.atl.emftvm.util.EMFTVMUtil.removeMany(EMFTVMUtil.java:906)
  [emftvm.run] 	at org.eclipse.m2m.atl.emftvm.util.EMFTVMUtil.remove(EMFTVMUtil.java:696)
  [emftvm.run] 	at org.eclipse.m2m.atl.emftvm.impl.ExecEnvImpl$DeletionEntry.process(ExecEnvImpl.java:221)
  [emftvm.run] 	... 27 more
```

**Comment by dwagelaar** [comment]
Atached zipped Eclipse project to reproduce.
[UMLRemove.zip](https://github.com/user-attachments/files/17013148/UMLRemove.zip)

**Comment by dwagelaar** [comment]
Problem still occurs:

```
  [emftvm.run] org.eclipse.m2m.atl.emftvm.util.VMException: Error deleting extension_unnamed1:UML!ExtensionEnd.lowerValue from :UML!LiteralInteger: Cannot invoke "org.eclipse.emf.ecore.resource.Resource.getContents()" because "vResource" is null
  [emftvm.run] at rule removes@applier(/StandardProfileConvertor_Gen/StandardProfile_Convertor.atl)
  [emftvm.run] 	Local variables: [1860251c:TRACE!TraceLink, :UML!LiteralInteger]
  [emftvm.run] at static EMFTVM!ExecEnv::main() : Object(/StandardProfileConvertor_Gen/StandardProfile_Convertor.atl)
  [emftvm.run] 	Local variables: []
  [emftvm.run] 	at org.eclipse.m2m.atl.emftvm.impl.ExecEnvImpl$DeletionEntry.process(ExecEnvImpl.java:227)
  [emftvm.run] 	at org.eclipse.m2m.atl.emftvm.impl.ExecEnvImpl.deleteQueue(ExecEnvImpl.java:2387)
  [emftvm.run] 	at org.eclipse.m2m.atl.emftvm.impl.ExecEnvImpl.matchAllSingle(ExecEnvImpl.java:2239)
  [emftvm.run] 	at org.eclipse.m2m.atl.emftvm.impl.ExecEnvImpl.run(ExecEnvImpl.java:2075)
  [emftvm.run] 	at org.eclipse.m2m.atl.emftvm.ant.RunTask.runForOutputModelSet(RunTask.java:357)
  [emftvm.run] 	at org.eclipse.m2m.atl.emftvm.ant.RunTask.runForInOutModelSet(RunTask.java:320)
  [emftvm.run] 	at org.eclipse.m2m.atl.emftvm.ant.RunTask.runForInputModelSet(RunTask.java:298)
  [emftvm.run] 	at org.eclipse.m2m.atl.emftvm.ant.RunTask.innerExecute(RunTask.java:276)
  [emftvm.run] 	at org.eclipse.m2m.atl.emftvm.ant.EMFTVMTask.execute(EMFTVMTask.java:98)
  [emftvm.run] 	at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:299)
  [emftvm.run] 	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
  [emftvm.run] 	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
  [emftvm.run] 	at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:99)
  [emftvm.run] 	at org.apache.tools.ant.Task.perform(Task.java:350)
  [emftvm.run] 	at org.apache.tools.ant.Target.execute(Target.java:449)
  [emftvm.run] 	at org.apache.tools.ant.Target.performTasks(Target.java:470)
  [emftvm.run] 	at org.apache.tools.ant.Project.executeSortedTargets(Project.java:1401)
  [emftvm.run] 	at org.apache.tools.ant.Project.executeTarget(Project.java:1374)
  [emftvm.run] 	at org.apache.tools.ant.helper.DefaultExecutor.executeTargets(DefaultExecutor.java:41)
  [emftvm.run] 	at org.eclipse.ant.internal.core.ant.EclipseDefaultExecutor.executeTargets(EclipseDefaultExecutor.java:34)
  [emftvm.run] 	at org.apache.tools.ant.Project.executeTargets(Project.java:1264)
  [emftvm.run] 	at org.eclipse.ant.internal.core.ant.InternalAntRunner.run(InternalAntRunner.java:714)
  [emftvm.run] 	at org.eclipse.ant.internal.core.ant.InternalAntRunner.run(InternalAntRunner.java:530)
  [emftvm.run] 	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
  [emftvm.run] 	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
  [emftvm.run] 	at org.eclipse.ant.core.AntRunner.run(AntRunner.java:369)
  [emftvm.run] 	at org.eclipse.ant.internal.launching.launchConfigurations.AntLaunchDelegate.lambda$0(AntLaunchDelegate.java:279)
  [emftvm.run] 	at java.base/java.lang.Thread.run(Thread.java:1583)
  [emftvm.run] Caused by: java.lang.NullPointerException: Cannot invoke "org.eclipse.emf.ecore.resource.Resource.getContents()" because "vResource" is null
  [emftvm.run] 	at org.eclipse.m2m.atl.emftvm.util.EMFTVMUtil.updateResource(EMFTVMUtil.java:1056)
  [emftvm.run] 	at org.eclipse.m2m.atl.emftvm.util.EMFTVMUtil.setSingle(EMFTVMUtil.java:744)
  [emftvm.run] 	at org.eclipse.m2m.atl.emftvm.util.EMFTVMUtil.remove(EMFTVMUtil.java:709)
  [emftvm.run] 	at org.eclipse.m2m.atl.emftvm.impl.ExecEnvImpl$DeletionEntry.process(ExecEnvImpl.java:221)
  [emftvm.run] 	... 27 more
```

**Comment by dwagelaar** [comment]
Fix integrated and confirmed in https://download.eclipse.org/mmt/atl/builds/nightly/N202409282105/
